# Generated by Django 5.0.4 on 2024-09-01 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('code', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'school',
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=250)),
                ('lastname', models.CharField(max_length=250)),
                ('gender', models.CharField(max_length=250)),
                ('school_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.school')),
            ],
            options={
                'db_table': 'students',
            },
        ),
        migrations.CreateModel(
            name='Classrooms',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('class_no', models.IntegerField()),
                ('subclass_no', models.IntegerField()),
                ('school_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom', to='apis.school')),
            ],
            options={
                'db_table': 'classrooms',
            },
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=250)),
                ('lastname', models.CharField(max_length=250)),
                ('gender', models.CharField(max_length=250)),
                ('in_classroom_list', models.ManyToManyField(related_name='teacher_in_classroom', to='apis.classrooms')),
                ('school_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='apis.school')),
            ],
            options={
                'db_table': 'teachers',
            },
        ),
        migrations.CreateModel(
            name='Student_list',
            fields=[
                ('students_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis.students')),
                ('classroom_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.classrooms')),
            ],
            options={
                'db_table': 'student_list',
            },
            bases=('apis.students',),
        ),
    ]
